Core.WebUI/Controllers/ReasonsController.cs
using Core.Application.DTOs;
using Core.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Core.WebUI.Controllers
{
    [Authorize]
    public class ReasonsController : Controller
    {
        private readonly IReasonService _reasonService;
        private readonly IUserProfileService _profileService;

        public ReasonsController(IReasonService reasonService, IUserProfileService profileService)
        {
            _reasonService = reasonService;
            _profileService = profileService;
        }

        public async Task<IActionResult> Index()
        {
            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var reasons = await _reasonService.GetReasonsAsync(profile);
            return View(reasons);
        }

        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        public async Task<IActionResult> Get(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var reason = await _reasonService.GetByIdAsync(id, profile);
            if (reason == null) return NotFound("Reason not found");

            return Json(reason);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ReasonDTOSet reasonDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (reasonDTO == null) return BadRequest("Invalid data");
            if (await _reasonService.GetByNameAsync(reasonDTO.Name, profile) != null) return Conflict("There is already a Reason with that name");

            reasonDTO.Id = Guid.NewGuid().ToString();
            await _reasonService.AddAsync(reasonDTO, profile);

            return Json(reasonDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, ReasonDTOSet reasonDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (reasonDTO == null) return BadRequest("Invalid data");
            reasonDTO.Id = id;

            await _reasonService.UpdateAsync(reasonDTO, profile);
            return Json(reasonDTO);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var reasonDTO = await _reasonService.GetByIdAsync(id, profile);
            if (reasonDTO == null) return NotFound("Reason not found");

            await _reasonService.RemoveAsync(id, profile);
            return Json(reasonDTO);
        }
    }
}

Core.WebUI/Controllers/TagsController.cs
using Core.Application.DTOs;
using Core.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Core.WebUI.Controllers
{

    [Authorize]
    public class TagsController : Controller
    {
        private readonly ITagService _tagService;
        private readonly IUserProfileService _profileService;

        public TagsController(ITagService tagService, IUserProfileService profileService)
        {
            _tagService = tagService;
            _profileService = profileService;
        }

        public async Task<IActionResult> Index()
        {
            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var tags = await _tagService.GetTagsAsync(profile);
            return View(tags);
        }

        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        public async Task<IActionResult> Get(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var tag = await _tagService.GetByIdAsync(id, profile);
            if (tag == null) return NotFound("Tag not found");

            return Json(tag);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TagDTOSet tagDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (tagDTO == null) return BadRequest("Invalid data");
            if (await _tagService.GetByNameAsync(tagDTO.Name, profile) != null) return Conflict("There is already a Tag with that name");

            tagDTO.Id = Guid.NewGuid().ToString();
            await _tagService.AddAsync(tagDTO, profile);

            return Json(tagDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, TagDTOSet tagDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (tagDTO == null) return BadRequest("Invalid data");
            tagDTO.Id = id;

            await _tagService.UpdateAsync(tagDTO, profile);
            return Json(tagDTO);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var tagDTO = await _tagService.GetByIdAsync(id, profile);
            if (tagDTO == null) return NotFound("Tag not found");

            await _tagService.RemoveAsync(id, profile);
            return Json(tagDTO);
        }

    }
}

Core.WebUI/Controllers/TransportTypesController.cs
using Core.Application.DTOs;
using Core.Application.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Core.WebUI.Controllers
{
    [Authorize]
    public class TransportTypesController : Controller
    {
        private readonly ITransportTypeService _typeService;
        private readonly IUserProfileService _profileService;

        public TransportTypesController(ITransportTypeService typeService, IUserProfileService profileService)
        {
            _typeService = typeService;
            _profileService = profileService;
        }

        public async Task<IActionResult> Index()
        {
            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var types = await _typeService.GetTransportTypesAsync(profile);
            return View(types);
        }

        public async Task<IActionResult> Get(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var type = await _typeService.GetByIdAsync(id, profile);
            if (type == null) return NotFound("Transport Type not found");

            return Json(type);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransportTypeDTOSet typeDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (typeDTO == null) return BadRequest("Invalid data");
            if (await _typeService.GetByNameAsync(typeDTO.Name, profile) != null) return Conflict("There is already a Transport Type with that name");

            typeDTO.Id = Guid.NewGuid().ToString();
            await _typeService.AddAsync(typeDTO, profile);

            return Json(typeDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, TransportTypeDTOSet typeDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (typeDTO == null) return BadRequest("Invalid data");
            typeDTO.Id = id;

            await _typeService.UpdateAsync(typeDTO, profile);
            return Json(typeDTO);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var typeDTO = await _typeService.GetByIdAsync(id, profile);
            if (typeDTO == null) return NotFound("Transport Type not found");

            await _typeService.RemoveAsync(id, profile);
            return Json(typeDTO);
        }
    }
}

Core.WebUI/Controllers/TransportsController.cs
using Core.Application.DTOs;
using Core.Application.Interfaces;
using Core.WebUI.ViewModels.Transports;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Core.WebUI.Controllers
{
    [Authorize]
    public class TransportsController : Controller
    {
        private readonly ITransportService _transportService;
        private readonly ITransportTypeService _typeService;
        private readonly ITagService _tagService;
        private readonly IReasonService _reasonService;
        private readonly IUserProfileService _profileService;

        public TransportsController(ITransportService transportService, ITransportTypeService typeService,
            ITagService tagService, IReasonService reasonService, IUserProfileService profileService)
        {
            _transportService = transportService;
            _typeService = typeService;
            _tagService = tagService;
            _reasonService = reasonService;
            _profileService = profileService;
        }

        public async Task<IActionResult> Index(DateTime? start, DateTime? end)
        {
            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            ViewBag.StartDate = start.HasValue ? start.Value.ToString("dd/MM/yyyy 00:00") : "";
            ViewBag.EndDate = end.HasValue ? end.Value.ToString("dd/MM/yyyy 23:59") : "";

            var types = await _typeService.GetTransportTypesAsync(profile);
            ViewBag.Types = types;

            var tags = await _tagService.GetTagsAsync(profile);
            ViewBag.Tags = tags;

            var reasons = await _reasonService.GetReasonsAsync(profile);
            ViewBag.Reasons = reasons;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(TimelineViewModel model)
        {
            if (!ModelState.IsValid) 
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var transports = await _transportService.GetTransportsByRangeAsync(model.StartDate, model.EndDate, profile);
            if (!transports.Any()) return PartialView("_EmptyTimeline");
            return PartialView("_Timeline", transports);
        }

        public async Task<IActionResult> Get(string id)
        {
            if (!ModelState.IsValid) 
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var transport = await _transportService.GetByIdAsync(id, profile);
            if (transport == null) return NotFound("Transport not found");

            return Json(transport);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TransportDTOSet transportDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (transportDTO == null) return BadRequest("Invalid data");

            transportDTO.Id = Guid.NewGuid().ToString();

            foreach(var tag in transportDTO.TransportTags)
                if(string.IsNullOrEmpty(tag.Id)) tag.Id = Guid.NewGuid().ToString();

            await _transportService.AddAsync(transportDTO, profile);

            return Json(transportDTO);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, TransportDTOSet transportDTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            if (transportDTO == null) return BadRequest("Invalid data");
            transportDTO.Id = id;

            if(transportDTO.TransportTags != null)
                foreach (var tag in transportDTO.TransportTags)
                    if (string.IsNullOrEmpty(tag.Id)) tag.Id = Guid.NewGuid().ToString();


            await _transportService.UpdateAsync(transportDTO, profile);
            return Json(transportDTO);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (!ModelState.IsValid)
                return BadRequest(Utilities.InvalidStateMessages(ModelState));

            var profile = await _profileService.GetByEmailAsync(User.Identity.Name);
            if (profile == null) return Unauthorized("Account not found");

            var transportDTO = await _transportService.GetByIdAsync(id, profile);
            if (transportDTO == null) return NotFound("Transport not found");

            await _transportService.RemoveAsync(id, profile);
            return Json(transportDTO);
        }
    }
}

Core.WebUI/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>
        &copy; @DateTime.Now.Year

        @if (Html.IsDev())
        {
            <span class="development">(Development environment)</span>
        }
        else
        {
            <a href="https://github.com/coelhovictor">github.com/coelhovictor</a>
        }
    </strong>
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0.0.0
    </div>
</footer>

Core.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] | TransportControl</title>

    <link rel="apple-touch-icon" sizes="57x57" href="~/dist/images/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/dist/images/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/dist/images/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/dist/images/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/dist/images/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/dist/images/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/dist/images/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/dist/images/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/dist/images/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/dist/images/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/dist/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/dist/images/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/dist/images/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="~/dist/images/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/lib/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <link rel="stylesheet" href="~/lib/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/lib/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/lib/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="~/css/site.css">

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/dist/js/adminlte.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/moment/moment.min.js"></script>
    <script src="~/lib/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>
    <script src="~/lib/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
    <script src="~/lib/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="~/js/site.js"></script>

    <script src="~/lib/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.min.js"></script>
    <script src="~/lib/chart.js/Chart.min.js"></script>
</head>
<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed sidebar-collapse">
    <div class="wrapper">

        <div class="preloader flex-column justify-content-center align-items-center">
            <div class="logo animation__wobble" style="padding: 10px; font-size: 28px;"><i class="nav-icon fas fa-car"></i></div>
        </div>

        <partial name="_Navbar" />

        <partial name="_Siderbar" />

        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewData["Title"]</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
                                <li class="breadcrumb-item active">@ViewData["Title"]</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </section>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>

        <partial name="_Footer" />
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

Core.WebUI/Views/Shared/_Navbar.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<Core.Infra.Data.Identity.ApplicationUser> userManager;

@{ var currentUser = @User.UserProfile(userManager); }

<nav class="main-header navbar navbar-expand navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-action="Index" asp-controller="Home" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-action="Index" asp-controller="Transports" class="nav-link">Transports</a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link pt-0 mt-1" data-toggle="dropdown" href="#">
                @if (!string.IsNullOrEmpty(currentUser.Picture))
                {
                    <img class="profile-user user-small" src="@currentUser.Picture" />
                }
                else
                {
                    <div class="profile-user user-small">@currentUser.FirstName.ToUpper()[0]</div>
                }
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Profile</span>
                <div class="dropdown-divider"></div>
                <a title="Profile" asp-area="" asp-controller="Profile" asp-action="Index" 
                   class="user-block dropdown-item mb-2 mt-2">
                    @if (!string.IsNullOrEmpty(currentUser.Picture))
                    {
                        <img class="profile-user user-small" style="float: left;" src="@currentUser.Picture" />
                    }
                    else
                    {
                        <div class="profile-user user-small" style="float: left;">@currentUser.FirstName.ToUpper()[0]</div>
                    }
                    <span class="username">@currentUser.FirstName @currentUser.LastName</span>
                    <span class="description">@currentUser.Email</span>
                </a>
                <div class="dropdown-divider" style="width: 100%;"></div>
                <a title="Logout" asp-area="" asp-controller="Account" asp-action="Logout" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

Core.WebUI/Views/Shared/_Siderbar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a asp-action="Index" asp-controller="Home" class="brand-link">
        <div class="logo"><i class="nav-icon fas fa-car"></i></div>
        <span class="brand-text font-weight-light">TransportControl</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Home" class="nav-link @Html.IsActive("Index", "Home")">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Transports" class="nav-link @Html.IsActive("Index", "Transports")">
                        <i class="nav-icon fas fa-car"></i>
                        <p>
                            Transports
                        </p>
                    </a>
                </li>
                <li class="nav-header">OPTIONS</li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="TransportTypes" class="nav-link @Html.IsActive("Index", "TransportTypes")">
                        <i class="nav-icon fas fa-box"></i>
                        <p>
                            Transport Types
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Tags" class="nav-link @Html.IsActive("Index", "Tags")">
                        <i class="nav-icon fas fa-tag"></i>
                        <p>
                            Tags
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Reasons" class="nav-link @Html.IsActive("Index", "Reasons")">
                        <i class="nav-icon fas fa-sticky-note"></i>
                        <p>
                            Reasons
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>